apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-login
  namespace: devops-exam-teamk1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-login
  template:
    metadata:
      labels:
        app: api-login
    spec:
      imagePullSecrets:
      - name: registry-cw-cdg-co-th
      containers:
      - name: api-login
        image: registry.cw.cdg.co.th/devops-exam/teamk1/api-login:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: jwt-env
