env:
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
rules: 
  'semi': ['error', 'never']
overrides:
  - files:
      - '**/*.test.js'
  - env:
    - jest: true
